name: Linting & Formatting

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  get-changed-files:
    name: Get changed files
    runs-on: ubuntu-latest
    outputs:
      py_files: ${{ steps.changed.outputs.py_files }}
      js_files: ${{ steps.changed.outputs.js_files }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # needed for git diff
          ref: ${{ github.head_ref }}

      - name: Get changed Python and JavaScript files
        id: changed
        run: |
          PY_FILES=$(git diff --name-only origin/${{ github.base_ref }}...${{ github.head_ref }} | grep '\.py$' || true)
          JS_FILES=$(git diff --name-only origin/${{ github.base_ref }}...${{ github.head_ref }} | grep '\.js$' || true)

          echo "Python files: $PY_FILES"
          echo "JavaScript files: $JS_FILES"

          echo "py_files<<EOF" >> $GITHUB_OUTPUT
          echo "$PY_FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

          echo "js_files<<EOF" >> $GITHUB_OUTPUT
          echo "$JS_FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

  precommit:
    needs: get-changed-files
    if: ${{ needs.get-changed-files.outputs.py_files != '' || needs.get-changed-files.outputs.js_files != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install JS dependencies
        run: |
          cd sample-node-js
          yarn install --frozen-lockfile
          # npm ci is also OK

      - name: Install pre-commit
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv sync --dev
          source ./.venv/bin/activate
          pre-commit install

      - name: Run pre-commit
        run: |
          source .venv/bin/activate
          FILES="${{ needs.get-changed-files.outputs.py_files }} ${{ needs.get-changed-files.outputs.js_files }}"
          echo "Running pre-commit on files: $FILES"
          pre-commit run --files $FILES
      
      # In the current .pre-commit-config.yaml, I do not setup auto fix with Ruff,.. just checking code, developers have to fix it locally
      # Therefore, this code is necessary at this point.
      # - name: Auto commit
      #   run: |
      #     git add .
      #     git commit -m "auto commit after pre-commit fixed"
      #     git push 
