name: Lint Changed Python Files Only

on:
  pull_request:
    paths:
      - '**.py'

jobs:
  lint:
    name: Ruff + PyreFly on Changed Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for full git diff

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pyrefly

      - name: Get list of changed Python files
        id: changed
        run: |
          CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }}...${{ github.head_ref }} | grep '\.py$' || true)
          echo "changed_files=$CHANGED_FILES" >> $GITHUB_OUTPUT

      - name: Run Ruff on changed files
        if: steps.changed.outputs.changed_files != ''
        run: |
          echo "${{ steps.changed.outputs.changed_files }}" | xargs ruff check

      - name: Run PyreFly on changed files
        if: steps.changed.outputs.changed_files != ''
        run: |
          echo "${{ steps.changed.outputs.changed_files }}" | xargs pyrefly --strict
