name: Annotated Linting on Changed Files Only

on:
  pull_request:
  push:

jobs:
  review:
    name: Ruff + PyreFly on Changed Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed for git diff
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python tools
        run: |
          pip install --upgrade pip
          pip install ruff pyrefly

      - name: Get changed Python files
        id: changed
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            BASE=${{ github.event.pull_request.base.sha }}
            HEAD=${{ github.event.pull_request.head.sha }}
          else
            BASE=${{ github.event.before }}
            HEAD=${{ github.event.after }}
          fi

          echo "Comparing changes from $BASE to $HEAD"

          FILES=$(git diff --name-only $BASE $HEAD | grep '\.py$' || true)

          echo "$FILES"
          echo "changed_files<<EOF" >> $GITHUB_OUTPUT
          echo "$FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Run Ruff on changed files
        if: steps.changed.outputs.changed_files != ''
        run: |
          echo "${{ steps.changed.outputs.changed_files }}" | xargs ruff check --output-format=github

      - name: Typecheck
        run: |
          echo "${{ steps.changed.outputs.changed_files }}" | xargs pyrefly check
