name: Annotated Linting on Changed Files Only

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  get-changed-files:
    runs-on: ubuntu-latest
    outputs:
      py_files: ${{ steps.changed.outputs.py_files }}
      js_files: ${{ steps.changed.outputs.js_files }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # needed for git diff
          ref: ${{ github.head_ref }}

      - name: Get changed Python and JavaScript files
        id: changed
        run: |
          PY_FILES=$(git diff --name-only origin/${{ github.base_ref }}...${{ github.head_ref }} | grep '\.py$' || true)
          JS_FILES=$(git diff --name-only origin/${{ github.base_ref }}...${{ github.head_ref }} | grep '\.js$' | sed 's|^sample-node/||' || true)

          echo "Python files: $PY_FILES"
          echo "JavaScript files: $JS_FILES"

          echo "py_files<<EOF" >> $GITHUB_OUTPUT
          echo "$PY_FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

          echo "js_files<<EOF" >> $GITHUB_OUTPUT
          echo "$JS_FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

  check-python:
    needs: get-changed-files
    name: Ruff + PyreFly on changed files
    runs-on: ubuntu-latest
    if: ${{ needs.get-changed-files.outputs.py_files != '' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python tools
        run: |
          pip install --upgrade pip
          pip install ruff pyrefly

      - name: Run Ruff on changed files
        run: |
          echo "${{ needs.get-changed-files.outputs.py_files }}" | xargs ruff check --output-format=github

      - name: Typecheck
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          python3 -m pip install -r ./project1/requirements.txt -r ./project2/requirements.txt
          echo "${{ needs.get-changed-files.outputs.py_files }}" | xargs pyrefly check
      
  check-js:
    needs: get-changed-files
    name: Eslint on changed files
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sample-node
    if: ${{ needs.get-changed-files.outputs.js_files != '' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm ci

      - name: Run ESLint on changed files
        run: |
          echo "${{ needs.get-changed-files.outputs.js_files }}" | xargs npx eslint
