name: Annotated Linting on Changed Files Only

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    name: Ruff + PyreFly on Changed Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed for git diff
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python tools
        run: |
          pip install --upgrade pip
          pip install ruff pyrefly

      - name: Get changed Python files
        id: changed
        run: |
          FILES=$(git diff --name-only origin/${{ github.base_ref }}...${{ github.head_ref }} | grep '\.py$' || true)

          echo "$FILES"
          echo "changed_files<<EOF" >> $GITHUB_OUTPUT
          echo "$FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Run Ruff on changed files
        if: steps.changed.outputs.changed_files != ''
        run: |
          echo "${{ steps.changed.outputs.changed_files }}" | xargs ruff check --output-format=github

      - name: Typecheck
        run: |
          echo "${{ steps.changed.outputs.changed_files }}" | xargs pyrefly check
